//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.SolarMetodos {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://192.168.1.76/wsRelacionamentoCliente.asmx", ConfigurationName="SolarMetodos.wsRelacionamentoClienteSoap")]
    public interface wsRelacionamentoClienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.1.76/wsRelacionamentoCliente.asmx/ObterCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObterCliente(string strChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.1.76/wsRelacionamentoCliente.asmx/ObterCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObterClienteAsync(string strChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.1.76/wsRelacionamentoCliente.asmx/ObterEquipamentos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObterEquipamentos(string strChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.1.76/wsRelacionamentoCliente.asmx/ObterEquipamentos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObterEquipamentosAsync(string strChave);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsRelacionamentoClienteSoapChannel : SolarEP.SolarMetodos.wsRelacionamentoClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsRelacionamentoClienteSoapClient : System.ServiceModel.ClientBase<SolarEP.SolarMetodos.wsRelacionamentoClienteSoap>, SolarEP.SolarMetodos.wsRelacionamentoClienteSoap {
        
        public wsRelacionamentoClienteSoapClient() {
        }
        
        public wsRelacionamentoClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsRelacionamentoClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsRelacionamentoClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsRelacionamentoClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ObterCliente(string strChave) {
            return base.Channel.ObterCliente(strChave);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObterClienteAsync(string strChave) {
            return base.Channel.ObterClienteAsync(strChave);
        }
        
        public System.Data.DataTable ObterEquipamentos(string strChave) {
            return base.Channel.ObterEquipamentos(strChave);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObterEquipamentosAsync(string strChave) {
            return base.Channel.ObterEquipamentosAsync(strChave);
        }
    }
}
