//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_tipo
    {
        public adm_tipo()
        {
            this.administrador = new HashSet<administrador>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<administrador> administrador { get; set; }
    }
}
