//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria_produto
    {
        public categoria_produto()
        {
            this.produtos = new HashSet<produtos>();
        }
    
        public int id { get; set; }
        public string categoria_nome { get; set; }
    
        public virtual ICollection<produtos> produtos { get; set; }
    }
}
