//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciclo_robo
    {
        public int id { get; set; }
        public string metodo { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> ciclo { get; set; }
    }
}
