//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string arquivo_url { get; set; }
        public Nullable<System.DateTime> criacao { get; set; }
    }
}
