//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipamento_loja
    {
        public int id { get; set; }
        public int id_equipamento { get; set; }
        public int id_loja { get; set; }
    
        public virtual equipamentos equipamentos { get; set; }
        public virtual lojas lojas { get; set; }
    }
}
