//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gestao_campanha
    {
        public gestao_campanha()
        {
            this.campanha_foto = new HashSet<campanha_foto>();
            this.campanha_loja = new HashSet<campanha_loja>();
            this.listacompra_loja = new HashSet<listacompra_loja>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string url_foto { get; set; }
        public string descricao_curta { get; set; }
        public string descricao { get; set; }
        public Nullable<int> permissao_img { get; set; }
        public Nullable<int> aderir { get; set; }
        public string url_facebok { get; set; }
        public string url_twitter { get; set; }
        public string url_youtube { get; set; }
        public int id_tipocampanha { get; set; }
        public string url_arquivo { get; set; }
        public string url_ldpi { get; set; }
        public string url_mdpi { get; set; }
        public string url_hdpi { get; set; }
        public string url_xhdpi { get; set; }
        public string link { get; set; }
        public string link_nome { get; set; }
        public Nullable<int> permitir_lista { get; set; }
        public string iphone4 { get; set; }
        public string iphone5 { get; set; }
        public string iphone6 { get; set; }
        public string iphone6plus { get; set; }
        public string base64_foto { get; set; }
        public Nullable<int> ativa { get; set; }
        public string icon_image { get; set; }
    
        public virtual campanha_ativa campanha_ativa { get; set; }
        public virtual ICollection<campanha_foto> campanha_foto { get; set; }
        public virtual ICollection<campanha_loja> campanha_loja { get; set; }
        public virtual campanha_tipo campanha_tipo { get; set; }
        public virtual ICollection<listacompra_loja> listacompra_loja { get; set; }
    }
}
