//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class listacompra_loja
    {
        public int id { get; set; }
        public int id_loja { get; set; }
        public int id_campanha { get; set; }
    
        public virtual gestao_campanha gestao_campanha { get; set; }
        public virtual lojas lojas { get; set; }
    }
}
