//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtos
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string preco { get; set; }
        public string url_foto { get; set; }
        public Nullable<int> categoria_id { get; set; }
        public Nullable<int> codigo { get; set; }
    
        public virtual categoria_produto categoria_produto { get; set; }
    }
}
