//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SolardbEntities : DbContext
    {
        public SolardbEntities()
            : base("name=SolardbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adm_tipo> adm_tipo { get; set; }
        public virtual DbSet<administrador> administrador { get; set; }
        public virtual DbSet<ajuda> ajuda { get; set; }
        public virtual DbSet<backgrounds> backgrounds { get; set; }
        public virtual DbSet<campanha_ativa> campanha_ativa { get; set; }
        public virtual DbSet<campanha_foto> campanha_foto { get; set; }
        public virtual DbSet<campanha_loja> campanha_loja { get; set; }
        public virtual DbSet<campanha_tipo> campanha_tipo { get; set; }
        public virtual DbSet<categoria_produto> categoria_produto { get; set; }
        public virtual DbSet<checklist_codigo> checklist_codigo { get; set; }
        public virtual DbSet<checklist_equipamento> checklist_equipamento { get; set; }
        public virtual DbSet<documentos> documentos { get; set; }
        public virtual DbSet<equipamento_loja> equipamento_loja { get; set; }
        public virtual DbSet<equipamentos> equipamentos { get; set; }
        public virtual DbSet<faq> faq { get; set; }
        public virtual DbSet<gestao_campanha> gestao_campanha { get; set; }
        public virtual DbSet<grupos_faq> grupos_faq { get; set; }
        public virtual DbSet<listacompra_loja> listacompra_loja { get; set; }
        public virtual DbSet<loja_status> loja_status { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<produtos> produtos { get; set; }
        public virtual DbSet<solicitacao> solicitacao { get; set; }
        public virtual DbSet<status_pedido> status_pedido { get; set; }
        public virtual DbSet<uf> uf { get; set; }
        public virtual DbSet<visita_chamado> visita_chamado { get; set; }
        public virtual DbSet<visita_fotos> visita_fotos { get; set; }
        public virtual DbSet<visita_status> visita_status { get; set; }
        public virtual DbSet<log_acesso> log_acesso { get; set; }
        public virtual DbSet<ciclo_robo> ciclo_robo { get; set; }
        public virtual DbSet<configuracao> configuracao { get; set; }
        public virtual DbSet<visita> visita { get; set; }
        public virtual DbSet<lojas> lojas { get; set; }
    }
}
