//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitacao
    {
        public int id { get; set; }
        public string numero_comodato { get; set; }
        public string titulo { get; set; }
        public string descricao_problema { get; set; }
        public int id_loja { get; set; }
    
        public virtual lojas lojas { get; set; }
    }
}
