//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visita_chamado
    {
        public int id { get; set; }
        public Nullable<int> id_visita { get; set; }
        public string chamado { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual visita visita { get; set; }
    }
}
