//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visita
    {
        public visita()
        {
            this.visita_chamado = new HashSet<visita_chamado>();
            this.visita_fotos = new HashSet<visita_fotos>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_loja { get; set; }
        public Nullable<int> id_status { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public string contato { get; set; }
        public string data { get; set; }
        public string id_equipamento { get; set; }
        public string obs_admin { get; set; }
        public string EQFNR { get; set; }
        public string TYPBZ { get; set; }
        public string EQUNR { get; set; }
        public string HERST { get; set; }
        public string atualiza { get; set; }
        public string previsao { get; set; }
        public string tag_equipamento { get; set; }
    
        public virtual visita_status visita_status { get; set; }
        public virtual ICollection<visita_chamado> visita_chamado { get; set; }
        public virtual ICollection<visita_fotos> visita_fotos { get; set; }
        public virtual lojas lojas { get; set; }
    }
}
